language: python
python:
  - "3.6.6"
install:
  - pip install -r requirements.txt
env:
  - CONSUMER_KEY=X CONSUMER_SECRET=X ACCESS_TOKEN=X-X ACCESS_TOKEN_SECRET=X
script:
  - python -m unittest discover -s tests/test_config
  - python -m unittest discover -s tests/test_options
  - python -m unittest discover -s tests/test_discord
  - python -m unittest discover -s tests/test_python
